bool success_prev # did the previous action succeed?
string uuid_prev # prev action UUID
int8 action_type_prev # prev action_type

# the previous action can return details
context_action_framework/CutDetails cut_details
context_action_framework/LeverDetails lever_details
context_action_framework/MoveDetails move_details
context_action_framework/PushDetails push_details
context_action_framework/TurnOverDetails turn_over_details
context_action_framework/VisionDetails vice_details
context_action_framework/VisionDetails vision_details
---
bool success # is able to provide next action
string uuid
int8 action_type
# string action_block # json
context_action_framework/CutBlock cut_block
context_action_framework/LeverBlock lever_block
context_action_framework/MoveBlock move_block
context_action_framework/PushBlock push_block
context_action_framework/TurnOverBlock turn_over_block
context_action_framework/VisionBlock vice_block
context_action_framework/VisionBlock vision_block
