# int8 camera # from types Camera
# camera is now specified in the service call path
bool gap_detection
---
bool success
context_action_framework/VisionDetails vision_details
# sensor_msgs/Image image